version: 2
jobs:
  build:
    working_directory: /root
    docker:
      - image: jupyter/datascience-notebook
    steps:
      - run:
          name: Update
          command: apt-get update
      - run:
          name: Install ssh
          command: apt-get install -y openssh-client openssh-server
      - checkout
      - run:
          name: Install Dependencies
          command: python -m pip install --no-cache-dir -r requirements.txt
      - run:
          name: Install pyradiomics
          command: python setup.py install
      - run:
          name: Run tests
          command: nosetests
